FROM FROM tensorflow/tensorflow:latest-gpu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
	 apt-get -y install curl g++ python3 python3-pip python3-tk  nano libglib2.0-0 tree libsm6 libxext6 libxrender-dev
#RUN apt-get install python3

#RUN apt-get install python3-pip
RUN pip3 install pip --upgrade
RUN pip install numpy
RUN pip install scipy
RUN pip install matplotlib
#RUN pip install tensorflow-gpu
#RUN pip install tensorflow
RUN pip install Pillow
RUN pip install pypng
RUN pip install scikit_learn
RUN pip install opencv-python
RUN pip install jupyter
RUN pip install jupyterthemes
RUN pip install hyperas
RUN pip install pandas


RUN mkdir ~/akanu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
	 apt-get -y install curl g++ python3 python3-pip python3-tk  nano libglib2.0-0 tree libsm6 libxext6 libxrender-dev
#RUN apt-get install python3

#RUN apt-get install python3-pip
RUN pip3 install pip --upgrade
RUN pip install numpy
RUN pip install scipy
RUN pip install matplotlib
#RUN pip install tensorflow-gpu
#RUN pip install tensorflow
RUN pip install Pillow
RUN pip install pypng
RUN pip install scikit_learn
RUN pip install opencv-python
RUN pip install jupyter
RUN pip install jupyterthemes
RUN pip install hyperas
RUN pip install pandas


RUN mkdir ~/akanu
